# Generated by Django 3.2.6 on 2021-11-17 01:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order_Userr',
        ),
    ]
