# Generated by Django 3.2.6 on 2021-11-17 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_quantity'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
